version: 1

jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch
    working_directory: /home/circleci/allerID
    steps:
      - checkout
      - run:
          name: Install packages.
          command: |
            sudo apt-get install r-base
            sudo R -e 'install.packages("goldi", repo = "http://cran.utstat.utoronto.ca/")'
            sudo R -e 'install.packages("shiny", repo = "http://cran.utstat.utoronto.ca/")'
            sudo R -e 'install.packages("testthat", repo = "http://cran.utstat.utoronto.ca/")'
      - run:
          name: Run tests
          command: |
            R -e 'testthat::test_dir("tests/testthat/")' 
